#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

APP="$1"; DOKKU_APP_LISTEN_PORT="$2"; DOKKU_APP_LISTEN_IP="$3"

if [[ -f "$DOKKU_ROOT/$APP/CONTAINER.ws.1" ]]; then
  dokku_log_info1 "Configuring WebSockets on the web container's port via Nginx location"

  WS_ID=$(< "$DOKKU_ROOT/$APP/CONTAINER.ws.1")
  WS_IPADDR=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' $WS_ID)

  # make sure that app-specific nginx.conf include directory exists
  if [ ! -d "$DOKKU_ROOT/$APP/nginx.conf.d/" ]; then
    mkdir "$DOKKU_ROOT/$APP/nginx.conf.d/"
  fi

  APP_WS_NGINX_TEMPLATE="$DOKKU_ROOT/$APP/ws.conf.template"
  [[ -f "$APP_WS_NGINX_TEMPLATE" ]] && WS_NGINX_TEMPLATE="$APP_WS_NGINX_TEMPLATE" && dokku_log_info1 "Overriding default faye.conf with detected ws.conf.template"
  [[ -z "$WS_NGINX_TEMPLATE" ]] && WS_NGINX_TEMPLATE="$PLUGIN_AVAILABLE_PATH/ws-nginx-location/templates/ws.conf.template"

  WS_NGINX_CONF=$(mktemp -t "ws.conf.XXXXXX")
  eval "cat <<< \"$(< $WS_NGINX_TEMPLATE)\" >> $WS_NGINX_CONF"

  dokku_log_info1 "Creating nginx.conf.d/ws.conf"
  mv $WS_NGINX_CONF "$DOKKU_ROOT/$APP/nginx.conf.d/ws.conf"
fi
