#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

APP="$1"; DOKKU_APP_LISTEN_PORT="$2"; DOKKU_APP_LISTEN_IP="$3"

dokku_log_info1 "Configuring Faye on the web container's port via Nginx location"
dokku_log_info2 "APP:DOKKU_APP_LISTEN_PORT:DOKKU_APP_LISTEN_IP $APP:$DOKKU_APP_LISTEN_PORT:$DOKKU_APP_LISTEN_IP"
